# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: production_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - production_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: production_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - API_PREFIX=/api/v1
      - DEBUG=False
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - production_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: production_frontend
    restart: always
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - production_network

networks:
  production_network:
    driver: bridge

volumes:
  postgres_data:
